version: '3.2'
services:
  nest-project:
    build:
      context: ./notes-back-end
      dockerfile: 'Dockerfile'
    ports:
      - '4000:4000'
    environment: 
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - PORT=${PORT}

  notes-ui:
    build:
      context: ./notes-ui
    command: npm start
    ports:
      - "3000:3000"
    container_name: notes-ui